### ISSUE TITLE
Unable to download due to illegal file names

### ISSUE THREAD

**Issue by GitGhillie** [lopopylopy/mrbreakfasts_free_prompts#4]
Thank you for these prompts!

I did have a minor issue because I could not download this using `git clone` on Windows and when I then tried to download the zip and unpack it I got errors like:

![image](https://github.com/lopopylopy/mrbreakfasts_free_prompts/assets/23659539/c45d867f-fc69-48c8-b04e-2fe07090c82e)

This is because the `"` and `:` is not allowed in Windows filenames. Other than that I'm happy with this pack!

**Comment by lopopylopy** [comment]
I've checked the cloning on Windows after renaming all the files with illegal characters.

I hadn't considered that Windows had different illegal characters than Linux! Thanks
